// APPlICATIONS
export const SET_APPLICATIONS = 'SET_APPLICATIONS';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';

// AUTH
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

// PETS
export const SET_PETS = 'SET_PETS';
export const DELETE_PET = 'DELETE_PET';

// SHELTERS
export const SET_SHELTERS = 'SET_SHELTERS';
export const DELETE_SHELTER = 'DELETE_SHELTER';
